MvcOnlineTicariOtomasyon/Models/Siniflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class Departman
    {
        [Key]
        public int DepartmanId { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string DepartmanAd { get; set; }
        public bool Durum { get; set; }
        public ICollection<Personel> Personels { get; set; }
    }
}

MvcOnlineTicariOtomasyon/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class DepartmanController : Controller
    {
        // GET: Departman
        Context c = new Context();

        public ActionResult Index()
        {
            var degerler = c.Departmans.Where(x => x.Durum == true).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult DepartmanEkle() //aynı method 2 defa yazıldı. çünkü hem sayfa yüklerken hemde veri gönderirken çalıştırılacak.
        {
            return View();  // burada boş bir sayfa çalışacak
        }
        [HttpPost]
        public ActionResult DepartmanEkle(Departman d) //Departman sınıfından d türetildi.
        {
            d.Durum = true;
            c.Departmans.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");   //departman eklendi. kaydedildi. sonrasında beni bir aksiyona yönlendir dedik.
        }

        public ActionResult DepartmanSil(int id)
        {
            var dep = c.Departmans.Find(id);
            dep.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanGetir(int id)
        {
            var departman = c.Departmans.Find(id);
            return View("DepartmanGetir", departman);
        }

        public ActionResult DepartmanGuncelle(Departman d)
        {
            var dep = c.Departmans.Find(d.DepartmanId);  //dep olarak değişken oluşturuldu ve departmanid hafızaya alındı.
            dep.DepartmanAd = d.DepartmanAd;   //Departmans sınıfındaki departmanad a sağdaki d.departmanad değeri atandı
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanDetay(int id)
        {
            var degerler = c.Personels.Where(x => x.Departmanid == id).ToList();  //Aynı departmana ait personeli getiren sorgu kodu.
            var dpt = c.Departmans.Where(x => x.DepartmanId == id).Select(y => y.DepartmanAd).FirstOrDefault(); //tolist kullanılmamasının sebebi bir tablo değil tek bir değer getirilecek olması
            ViewBag.d = dpt; // yukarıdaki sorguyu viewbag.d altına aktardık.
            return View(degerler);

        }

        public ActionResult DepartmanPersonelSatis(int id)
        {
            var degerler=c.SatisHarekets.Where(x=>x.Personelid == id).ToList();
            var per=c.Personels.Where(x=>x.PersonelId==id).Select(y=>y.PersonelAd +" "+ y.PersonelSoyad).FirstOrDefault();
            ViewBag.dpers = per;
            return View(degerler);

        }
    }
}

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Departman Detay</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active" style="font-weight:bolder">@ViewBag.d Departmanına Ait Personel Listesi</li>
</ol>

<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Görsel</th>
        <th>Satışlar</th>

    </tr>

    @foreach (var x in Model)

    {
        <tr>
            <td>@x.PersonelId</td>
            <td>@x.PersonelAd</td>
            <td>@x.PersonelSoyad</td>
            <td>@x.PersonelGorsel</td>

            <td><a href="/Departman/DepartmanPersonelSatis/@x.PersonelId" class="btn btn-default" style="background-color:gold">Satışlar</a></td>
        </tr>

    }
</table>

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Ekle</h2>
<br />

<form class="form-group" method="post">
    @Html.LabelFor(x => x.DepartmanAd)
    @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Departman


    @{
        ViewBag.Title = "DepartmanGetir";
        Layout = "~/Views/Shared/AdminLayout.cshtml";
    }

    <br />
    <h2>Departman Güncelleme</h2>
    <br />

    @using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post)) //Bu sayfa yüklendikten sonra post işlemi gerçekleştiğinde hangi actionresultlar gerçekleşecekse onları sırayla
                                                                              // yazıyoruz. Sırayla Önce KategoriGuncelle Actionı oluşturduk, neyin içinde? Kategori İçinde. Ne zaman yapacak? Post olduğu zaman yapacak. bu sırayla yapılıyor
    {
        <div class="form-group">
            @Html.LabelFor(x => x.DepartmanAd)
            @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
            @Html.HiddenFor(x => x.DepartmanId)
        </div>
        <button class="btn btn-warning">Güncelle</button>
    }

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanPersonelSatis.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Departman Personel Satış</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active" style="font-weight:bolder">@ViewBag.dpers Satışları</li>
</ol>

<table class="table table-bordered">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var x in Model)
    {
    <tr>
        <td>@x.Satisid</td>
        <td>@x.Urun.UrunAd</td>
        <td>@x.Cari.CariAd  @x.Cari.CariSoyad</td>
        <td>@x.Fiyat</td>
        <td>@x.Adet</td>
        <td>@x.ToplamTutar</td>
        <td>@x.Tarih</td>
        <td><a href="#" class="btn btn-default" style="background-color:dodgerblue">Yazdır</a></td>

    </tr>
    }
</table>

MvcOnlineTicariOtomasyon/Views/Departman/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px;">
    <tr>
        <th> ID </th>
        <th> Departman Adı </th>
        <th>Sil  </th>
        <th> Güncelle </th>
        <th> Detay </th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td><b>@k.DepartmanId</b></td>
            <td>@k.DepartmanAd</td>
            <td><a href="/Departman/DepartmanSil/@k.DepartmanId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Departman/DepartmanGetir/@k.DepartmanId" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Departman/DepartmanDetay/@k.DepartmanId" class="btn btn-default" style="background-color:lightcoral;color:whitesmoke">Detay</a></td>
        </tr>
    }
</table>
<a href="/Departman/DepartmanEkle" class="btn btn-primary">Departman Ekle</a>