MvcOnlineTicariOtomasyon/Controllers/CariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class CariController : Controller
    {
        Context c = new Context();
        // GET: Cari
        public ActionResult Index()
        {
            var degerler = c.Cariler.Where(x => x.Durum == true).ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult CariEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CariEkle(Cariler Cr)
        {
            Cr.Durum = true;
            c.Cariler.Add(Cr);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CariSil(int id)
        {
            var cr = c.Cariler.Find(id);
            cr.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CariGetir(int id)
        {
            var cari = c.Cariler.Find(id);
            return View("CariGetir", cari);
        }

        public ActionResult CariGuncelle(Cariler p)
        {
            if (!ModelState.IsValid)
            {
                return View("CariGetir");
            }
            var cari = c.Cariler.Find(p.CariId);
            cari.CariAd = p.CariAd;
            cari.CariSoyad = p.CariSoyad;
            cari.CariSehir = p.CariSehir;
            cari.CariMail = p.CariMail;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriSatis(int id)
        {
            var degerler=c.SatisHarekets.Where(x=>x.Cariid == id).ToList();
            var cr=c.Cariler.Where(x=>x.CariId == id).Select(y=>y.CariAd + " " + y.CariSoyad).FirstOrDefault();
            ViewBag.cari=cr;
            return View(degerler);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Cari/CariEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Cariler
@{
    ViewBag.Title = "CariEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Cari Ekleme Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.CariAd)
    @Html.TextAreaFor(x => x.CariAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariSoyad)
    @Html.TextAreaFor(x => x.CariSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariSehir)
    @Html.TextAreaFor(x => x.CariSehir, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariMail)
    @Html.TextAreaFor(x => x.CariMail, new { @class = "form-control" })
    <br />
  
  
   
    <button class="btn btn-primary">Kaydet</button>
</form>

MvcOnlineTicariOtomasyon/Views/Cari/CariGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Cariler
@{
    ViewBag.Title = "CariGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Cari Güncelleme Ekranı</h2>
<br />

@using (Html.BeginForm("CariGuncelle","Cari",FormMethod.Post))
            {
    
        <div class="form-group">
            @Html.HiddenFor(x => x.CariId)
            @Html.LabelFor(x => x.CariAd)
            @Html.TextAreaFor(x => x.CariAd, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CariAd, "", new { @style = "color:red" })
            <br />
            @Html.LabelFor(x => x.CariSoyad)
            @Html.TextAreaFor(x => x.CariSoyad, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CariSoyad, "", new { @style = "color:red" })
            <br />
            @Html.LabelFor(x => x.CariSehir)
            @Html.TextAreaFor(x => x.CariSehir, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CariSehir, "", new { @style = "color:red" })
            <br />
            @Html.LabelFor(x => x.CariMail)
            @Html.TextAreaFor(x => x.CariMail, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CariMail, "", new { @style = "color:red" })
            <br />

            <button class="btn btn-default" style="background-color:yellowgreen">Güncelle</button>
        </div>
            }

MvcOnlineTicariOtomasyon/Views/Cari/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Cariler>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />

<table class="table table-striped">
    <tr>
        <th>Cari ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Mail</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>

    @foreach(var x in Model)
            {
        <tr>
            <td>@x.CariId</td>
            <td>@x.CariAd</td>
            <td>@x.CariSoyad</td>
            <td>@x.CariSehir</td>
            <td>@x.CariMail</td>
            <td><a href="/Cari/CariSil/@x.CariId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Cari/CariGetir/@x.CariId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Cari/MusteriSatis/@x.CariId" class="btn btn-default" style="background-color:lightcoral">Satış Geçmişi</a></td>
        </tr>

            }

</table>
<a href="/Cari/CariEkle/" class="btn btn-info">Yeni Cari Ekle</a>

MvcOnlineTicariOtomasyon/Views/Cari/MusteriSatis.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "MusteriSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active" style="font-weight:bolder">@ViewBag.cari Müşterisinin Satışları</li>
</ol>

<table class="table table-bordered">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Marka</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Satisid</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Urun.Marka</td>
            <td>@x.Personel.PersonelAd @x.Personel.PersonelSoyad</td>
            <td>@x.Fiyat</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
            <td><a href="#" class="btn btn-default" style="background-color:dodgerblue">Yazdır</a></td>

        </tr>
    }
</table>